# Generated by Django 2.2.4 on 2019-11-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='county',
        ),
    ]
